//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DevExpress.Persistent.Base;
using DevExpress.Xpo;
using DevExpress.ExpressApp.Security.Strategy;
namespace ProjectSchedule.Module.BusinessObjects
{
  [DefaultClassOptions]
  [DevExpress.Persistent.Base.ImageNameAttribute("BO_Role")]
  public partial class ApplicationRole : SecuritySystemRoleBase
  {
    public ApplicationRole(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    [Association("ProjectMembers-ApplicationRoles")]
    public XPCollection<ProjectMember> ProjectMembers
    {
      get
      {
        return GetCollection<ProjectMember>("ProjectMembers");
      }
    }
  }
}
