//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace ProjectSchedule.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class BudgetTransfer : ProjectSchedule.Module.BusinessObjects.Comment
  {
    private ProjectSchedule.Module.BusinessObjects.BudgetAccount _toBudgetAccount;
    private ProjectSchedule.Module.BusinessObjects.BudgetAccount _fromBudgetAccount;
    private System.Decimal _amountSpent;
    private System.Decimal _amountPlanned;
    public BudgetTransfer(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.Decimal AmountPlanned
    {
      get
      {
        return _amountPlanned;
      }
      set
      {
        SetPropertyValue("AmountPlanned", ref _amountPlanned, value);
      }
    }
    public System.Decimal AmountSpent
    {
      get
      {
        return _amountSpent;
      }
      set
      {
        SetPropertyValue("AmountSpent", ref _amountSpent, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("OutcomeBudgetTransfers-FromBudgetAccount")]
    public ProjectSchedule.Module.BusinessObjects.BudgetAccount FromBudgetAccount
    {
      get
      {
        return _fromBudgetAccount;
      }
      set
      {
        SetPropertyValue("FromBudgetAccount", ref _fromBudgetAccount, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("IncomeBudgetTransfers-ToBudgetAccount")]
    public ProjectSchedule.Module.BusinessObjects.BudgetAccount ToBudgetAccount
    {
      get
      {
        return _toBudgetAccount;
      }
      set
      {
        SetPropertyValue("ToBudgetAccount", ref _toBudgetAccount, value);
      }
    }
  }
}
