//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace ProjectSchedule.Module.BusinessObjects
{
  [DefaultClassOptions]
  [DevExpress.Persistent.Base.ImageNameAttribute("BO_Report")]
  public partial class BudgetAccount : DevExpress.Persistent.BaseImpl.Task
  {
    private ProjectSchedule.Module.BusinessObjects.ProjectResource _projectResource;
    private ProjectSchedule.Module.BusinessObjects.ProjectMember _projectMember;
    private ProjectSchedule.Module.BusinessObjects.ProjectTask _projectTask;
    private System.Decimal _amountSpent;
    private System.Decimal _amountPlanned;
    public BudgetAccount(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.Decimal AmountPlanned
    {
      get
      {
        return _amountPlanned;
      }
      set
      {
        SetPropertyValue("AmountPlanned", ref _amountPlanned, value);
      }
    }
    public System.Decimal AmountSpent
    {
      get
      {
        return _amountSpent;
      }
      set
      {
        SetPropertyValue("AmountSpent", ref _amountSpent, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("BudgetPlanningAndUsages-BudgetAccount")]
    public XPCollection<ProjectSchedule.Module.BusinessObjects.BudgetPlanningAndUsage> BudgetPlanningAndUsages
    {
      get
      {
        return GetCollection<ProjectSchedule.Module.BusinessObjects.BudgetPlanningAndUsage>("BudgetPlanningAndUsages");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("IncomeBudgetTransfers-ToBudgetAccount")]
    public XPCollection<ProjectSchedule.Module.BusinessObjects.BudgetTransfer> IncomeBudgetTransfers
    {
      get
      {
        return GetCollection<ProjectSchedule.Module.BusinessObjects.BudgetTransfer>("IncomeBudgetTransfers");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("OutcomeBudgetTransfers-FromBudgetAccount")]
    public XPCollection<ProjectSchedule.Module.BusinessObjects.BudgetTransfer> OutcomeBudgetTransfers
    {
      get
      {
        return GetCollection<ProjectSchedule.Module.BusinessObjects.BudgetTransfer>("OutcomeBudgetTransfers");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("BudgetAccounts-ProjectTask")]
    public ProjectSchedule.Module.BusinessObjects.ProjectTask ProjectTask
    {
      get
      {
        return _projectTask;
      }
      set
      {
        SetPropertyValue("ProjectTask", ref _projectTask, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("BudgetAccounts-ProjectMember")]
    public ProjectSchedule.Module.BusinessObjects.ProjectMember ProjectMember
    {
      get
      {
        return _projectMember;
      }
      set
      {
        SetPropertyValue("ProjectMember", ref _projectMember, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("BudgetAccounts-ProjectResource")]
    public ProjectSchedule.Module.BusinessObjects.ProjectResource ProjectResource
    {
      get
      {
        return _projectResource;
      }
      set
      {
        SetPropertyValue("ProjectResource", ref _projectResource, value);
      }
    }
  }
}
