//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace ProjectSchedule.Module.BusinessObjects
{
  [DefaultClassOptions]
  [DevExpress.ExpressApp.DC.XafDefaultPropertyAttribute("Text")]
  [DevExpress.Persistent.Base.ImageNameAttribute("BO_Note")]
  public partial class Comment : Note
  {
    private ProjectSchedule.Module.BusinessObjects.ProjectMember _projectMember;
    public Comment(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    [DevExpress.Xpo.AssociationAttribute("Comments-ProjectTasks")]
    public XPCollection<ProjectSchedule.Module.BusinessObjects.ProjectTask> ProjectTasks
    {
      get
      {
        return GetCollection<ProjectSchedule.Module.BusinessObjects.ProjectTask>("ProjectTasks");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Comments-ProjectMember")]
    public ProjectSchedule.Module.BusinessObjects.ProjectMember ProjectMember
    {
      get
      {
        return _projectMember;
      }
      set
      {
        SetPropertyValue("ProjectMember", ref _projectMember, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Attachments-Comment")]
    public XPCollection<ProjectSchedule.Module.BusinessObjects.Attachment> Attachments
    {
      get
      {
        return GetCollection<ProjectSchedule.Module.BusinessObjects.Attachment>("Attachments");
      }
    }
    public override void AfterConstruction()
    {
        base.AfterConstruction();

        DateTime = System.DateTime.Now;
    }
  }
}
