//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace ProjectSchedule.Module.BusinessObjects
{
  [DefaultClassOptions]
  [DevExpress.Persistent.Base.ImageNameAttribute("BO_Organization")]
  public partial class Company : Organization
  {
    public Company(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    [DevExpress.Xpo.AssociationAttribute("ProjectMembers-WorkForCompanies")]
    public XPCollection<ProjectSchedule.Module.BusinessObjects.ProjectMember> ProjectMembers
    {
      get
      {
        return GetCollection<ProjectSchedule.Module.BusinessObjects.ProjectMember>("ProjectMembers");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Attachments-Company")]
    public XPCollection<ProjectSchedule.Module.BusinessObjects.Attachment> Attachments
    {
      get
      {
        return GetCollection<ProjectSchedule.Module.BusinessObjects.Attachment>("Attachments");
      }
    }
  }
}
