//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace ProjectSchedule.Module.BusinessObjects
{
  [DefaultClassOptions]
  [DevExpress.Persistent.Base.ImageNameAttribute("BO_Role")]
  public partial class ProjectRole : RoleBase
  {
    public ProjectRole(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    [DevExpress.Xpo.AssociationAttribute("TaskMemberRoles-ProjectRole")]
    public XPCollection<ProjectSchedule.Module.BusinessObjects.TaskMemberRole> TaskMemberRoles
    {
      get
      {
        return GetCollection<ProjectSchedule.Module.BusinessObjects.TaskMemberRole>("TaskMemberRoles");
      }
    }
  }
}
