//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace ProjectSchedule.Module.BusinessObjects
{
  [DefaultClassOptions]
  [DevExpress.Persistent.Base.ImageNameAttribute("Action_Security_ChangePassword")]
  public partial class TaskMemberRole : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private ProjectSchedule.Module.BusinessObjects.ProjectTask _projectTask;
    private ProjectSchedule.Module.BusinessObjects.ProjectMember _grantedByMember;
    private ProjectSchedule.Module.BusinessObjects.ProjectMember _projectMember;
    private ProjectSchedule.Module.BusinessObjects.ProjectRole _projectRole;
    public TaskMemberRole(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    [DevExpress.Xpo.AssociationAttribute("TaskMemberRoles-ProjectRole")]
    public ProjectSchedule.Module.BusinessObjects.ProjectRole ProjectRole
    {
      get
      {
        return _projectRole;
      }
      set
      {
        SetPropertyValue("ProjectRole", ref _projectRole, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("TaskMemberRoles-ProjectMember")]
    public ProjectSchedule.Module.BusinessObjects.ProjectMember ProjectMember
    {
      get
      {
        return _projectMember;
      }
      set
      {
        SetPropertyValue("ProjectMember", ref _projectMember, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("TaskMemberRolesGranted-GrantedByMember")]
    public ProjectSchedule.Module.BusinessObjects.ProjectMember GrantedByMember
    {
      get
      {
        return _grantedByMember;
      }
      set
      {
        SetPropertyValue("GrantedByMember", ref _grantedByMember, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("TaskMemberRoles-ProjectTask")]
    public ProjectSchedule.Module.BusinessObjects.ProjectTask ProjectTask
    {
      get
      {
        return _projectTask;
      }
      set
      {
        SetPropertyValue("ProjectTask", ref _projectTask, value);
      }
    }
  }
}
